In [440]:
path_to_data = "/mnt/Data6/Enze/transcription_pipeline/Data/2025-06-17-Enze/hbP2WT_MCP-mSG_His-RFP005/collated_dataset"

In [441]:
import pickle
import pandas as pd
import numpy as np

In [442]:
with open(path_to_data + "/collated_frame_metadata_ch00.pkl", "rb") as f:
    metadata_ch00 = pickle.load(f)

with open(path_to_data + "/collated_frame_metadata_ch01.pkl", "rb") as f:
    metadata_ch01 = pickle.load(f)

with open(path_to_data + "/collated_frame_metadata_ch02.pkl", "rb") as f:
    metadata_ch02 = pickle.load(f)

t_all = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
t_1 = np.array([0, 1, 2, 3, 4, 5, 6])

In [443]:
metadata_ch00['t_s']

array([[2.54845300e-01, 1.27068130e+00, 2.26338330e+00, ...,
        1.75457723e+01, 1.84927113e+01, 1.94630363e+01],
       [6.99910130e+00, 7.94262830e+00, 8.88754730e+00, ...,
        2.42618213e+01, 2.52086333e+01, 2.62041133e+01],
       [1.36447493e+01, 1.46155813e+01, 1.55856533e+01, ...,
        3.10453673e+01, 3.19896513e+01, 3.29584573e+01],
       ...,
       [1.19525349e+03, 1.19617363e+03, 1.19711779e+03, ...,
        1.21259615e+03, 1.21356585e+03, 1.21455489e+03],
       [1.20189586e+03, 1.20286379e+03, 1.20385788e+03, ...,
                   nan,            nan,            nan],
       [1.20881142e+03, 1.20973560e+03, 1.21068141e+03, ...,
                   nan,            nan,            nan]])

In [444]:
metadata_ch00['t_s'][-1]

array([1208.8114153, 1209.7356043, 1210.6814093, 1211.6045873,
       1212.5961533, 1213.5658493, 1214.5548873,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan])

In [445]:
metadata_ch00['t_s'][-1][:7]

array([1208.8114153, 1209.7356043, 1210.6814093, 1211.6045873,
       1212.5961533, 1213.5658493, 1214.5548873])

In [446]:
k_1, b_1 = np.polyfit(t_1, metadata_ch00['t_s'][-1][:7], 1)

In [447]:
m1_pred = k_1 * t_all + b_1
print(m1_pred)

[1208.77795266 1209.7352973  1210.69264194 1211.64998659 1212.60733123
 1213.56467587 1214.52202051 1215.47936516 1216.4367098  1217.39405444
 1218.35139909 1219.30874373 1220.26608837 1221.22343301 1222.18077766
 1223.1381223  1224.09546694 1225.05281159 1226.01015623 1226.96750087
 1227.92484551]


In [448]:
metadata_ch00['t_s'][-1] = m1_pred

In [449]:
metadata_ch00['t_s'][-2]

array([1201.8958633, 1202.8637903, 1203.8578843, 1204.8469213,
       1205.8391193, 1206.8301793, 1207.8195963, 1208.8114153,
       1209.7356043, 1210.6814093, 1211.6045873, 1212.5961533,
       1213.5658493, 1214.5548873,          nan,          nan,
                nan,          nan,          nan,          nan,
                nan])

In [450]:
metadata_ch00['t_s'][-2][:14]

array([1201.8958633, 1202.8637903, 1203.8578843, 1204.8469213,
       1205.8391193, 1206.8301793, 1207.8195963, 1208.8114153,
       1209.7356043, 1210.6814093, 1211.6045873, 1212.5961533,
       1213.5658493, 1214.5548873])

In [451]:
t_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

In [452]:
k_2, b_2 = np.polyfit(t_2, metadata_ch00['t_s'][-2][:14], 1)

In [453]:
m2_pred = k_2 * t_all + b_2
print(m2_pred)

[1201.9336959  1202.90547082 1203.87724574 1204.84902066 1205.82079557
 1206.79257049 1207.76434541 1208.73612033 1209.70789525 1210.67967017
 1211.65144509 1212.62322001 1213.59499492 1214.56676984 1215.53854476
 1216.51031968 1217.4820946  1218.45386952 1219.42564444 1220.39741935
 1221.36919427]


In [454]:
metadata_ch00['t_s'][-2] = m2_pred

In [455]:
print(k_1, k_2, b_1, b_2)

0.9573446428571177 0.9717749186813326 1208.7779526571426 1201.9336959


In [456]:
metadata_ch00['t_s']

array([[2.54845300e-01, 1.27068130e+00, 2.26338330e+00, ...,
        1.75457723e+01, 1.84927113e+01, 1.94630363e+01],
       [6.99910130e+00, 7.94262830e+00, 8.88754730e+00, ...,
        2.42618213e+01, 2.52086333e+01, 2.62041133e+01],
       [1.36447493e+01, 1.46155813e+01, 1.55856533e+01, ...,
        3.10453673e+01, 3.19896513e+01, 3.29584573e+01],
       ...,
       [1.19525349e+03, 1.19617363e+03, 1.19711779e+03, ...,
        1.21259615e+03, 1.21356585e+03, 1.21455489e+03],
       [1.20193370e+03, 1.20290547e+03, 1.20387725e+03, ...,
        1.21942564e+03, 1.22039742e+03, 1.22136919e+03],
       [1.20877795e+03, 1.20973530e+03, 1.21069264e+03, ...,
        1.22601016e+03, 1.22696750e+03, 1.22792485e+03]])

In [457]:
with open(path_to_data + "/collated_frame_metadata_ch00.pkl", 'wb') as f:  # 'wb' means write in binary mode
    pickle.dump(metadata_ch00, f)

In [458]:
metadata_ch01['t_s']

array([[2.54845300e-01, 1.27068130e+00, 2.26338330e+00, ...,
        1.75457723e+01, 1.84927113e+01, 1.94630363e+01],
       [6.99910130e+00, 7.94262830e+00, 8.88754730e+00, ...,
        2.42618213e+01, 2.52086333e+01, 2.62041133e+01],
       [1.36447493e+01, 1.46155813e+01, 1.55856533e+01, ...,
        3.10453673e+01, 3.19896513e+01, 3.29584573e+01],
       ...,
       [1.19525349e+03, 1.19617363e+03, 1.19711779e+03, ...,
        1.21259615e+03, 1.21356585e+03, 1.21455489e+03],
       [1.20189586e+03, 1.20286379e+03, 1.20385788e+03, ...,
                   nan,            nan,            nan],
       [1.20881142e+03, 1.20973560e+03, 1.21068141e+03, ...,
                   nan,            nan,            nan]])

In [459]:
metadata_ch01['t_s'] =metadata_ch00['t_s']

In [460]:
with open(path_to_data + "/collated_frame_metadata_ch01.pkl", 'wb') as f:  # 'wb' means write in binary mode
    pickle.dump(metadata_ch01, f)

In [461]:
metadata_ch02['t_s']

array([[2.54845300e-01, 1.27068130e+00, 2.26338330e+00, ...,
        1.75457723e+01, 1.84927113e+01, 1.94630363e+01],
       [6.99910130e+00, 7.94262830e+00, 8.88754730e+00, ...,
        2.42618213e+01, 2.52086333e+01, 2.62041133e+01],
       [1.36447493e+01, 1.46155813e+01, 1.55856533e+01, ...,
        3.10453673e+01, 3.19896513e+01, 3.29584573e+01],
       ...,
       [1.19525349e+03, 1.19617363e+03, 1.19711779e+03, ...,
        1.21259615e+03, 1.21356585e+03, 1.21455489e+03],
       [1.20189586e+03, 1.20286379e+03, 1.20385788e+03, ...,
                   nan,            nan,            nan],
       [1.20881142e+03, 1.20973560e+03, 1.21068141e+03, ...,
                   nan,            nan,            nan]])

In [462]:
metadata_ch02['t_s'] =metadata_ch00['t_s']

In [463]:
with open(path_to_data + "/collated_frame_metadata_ch02.pkl", 'wb') as f:  # 'wb' means write in binary mode
    pickle.dump(metadata_ch02, f)